### ISSUE TITLE
v1.0.0 plugin bundle broken link

### ISSUE THREAD

**Issue by barryhaertel** [nathanaelhoun/mattermost-plugin-broomer#17]
### Describe the bug

On https://github.com/nathanaelhoun/mattermost-plugin-broomer/releases/tag/v1.0.0
the release section is missing what one would expect to be com.github.nathanaelhoun.plugin-broomer-1.0.0.tar.gz but it is not there

there is a link in the release notes that says [Click here to download the plugin bundle.](https://216-271894806-gh.circle-artifacts.com/0/dist/com.github.nathanaelhoun.plugin-broomer-1.0.0.tar.gz)

This link is invalid

### Expected behavior

plugin bundle download

### Steps to reproduce

read above

### Mattermost and plugin version

n/a

**Comment by nathanaelhoun** [comment]
Hi @systemswizard, thanks for reporting. I have uploaded the tar.gz as a GitHub asset, let me know if there is any problem with it!

**Comment by nathanaelhoun** [comment]
I'm going to mark this issue as resolved as the assets has been uploaded to GitHub. Feel free to ping me if there is anything wrong with the release :-)
